services:
    sqlserver:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=yourStrongPassword12#
        ports:
            - 1433:1433
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - taskboard_network
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
    web_app:
        container_name: web_app
        build:
            dockerfile: ./TaskBoard.WebApp/Dockerfile
        ports:
            - 5000:80
        restart: on-failure
        networks:
            - taskboard_network
networks:
    taskboard_network:
        external: true
        name: taskboard_network
volumes:
    sqldata:
        external: true
        name: sqldata