version: 3.8
services:
    web:
        ports:
            - 8000:8000
        build: .
        volumes:
            - ./static:/app/staticfiles
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
            - DEBUG=False
        image: simplepageapp
        networks:
            - dimo
networks:
  dimo: